routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionsController')->except('show');

//Route:post('questions/{question}/answers', 'AnswersController@store')->name('answers.store');

Route::resource('questions.answers', 'AnswersController')->only(['index', 'store', 'edit', 'update', 'destroy']);

//Route::resource('questions.answers', 'AnswersController')->except(['index', 'create', 'show']);

Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');

Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorite', 'FavoriteController@store')->name('questions.favorite');

Route::delete('/questions/{question}/favorite', 'FavoriteController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote', 'VoteQuestionController');

Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Null_;

class Answer extends Model
{
    use VotableTrait;

    protected $fillable = ['body', 'user_id'];

    protected $appends = ['created_date', 'body_html', 'is_best'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function getBodyHtmlAttribute()
    {
        return clean(\Parsedown::instance()->text($this->body));
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public function isBest()
    {
        return $this->id === $this->question->best_answer_id;
    }

    public static function boot()
    {
        parent::boot();

        static::created(function ($answer)
        {
            $answer->question()->increment('answers_count');
        });

        static::deleted(function ($answer)
        {
            $question = $answer->question;
            $question->decrement('answers_count');

            if($question->best_answer_id === $answer->id)
            {
                $question->best_answer_id = NULL;
                $question->save();
            }
        });
    }
}

resources/views/shared/_accept.blade.php
@can('accept', $model)
    <a href="" title="Mark this answer as best answer"
       class="{{ $model->status }} mt-2"
       onclick="event.preventDefault(); document.getElementById('accept-answer-{{ $model->id }}').submit()">
        <i class="fas fa-check fa-2x"></i>
    </a>
    <form action="{{ route('answers.accept', $model->id) }}" id="accept-answer-{{ $model->id }}" method="post" style="display: none;">
        @csrf
    </form>
@else
    @if($model->is_best)
        <a href="" title="The question owner accepted this answer as best answer" class="{{ $model->status }} mt-2">
            <i class="fas fa-check fa-2x"></i>
        </a>
    @endif
@endcan

resources/views/shared/_favorite.blade.php
<a href="" title="Click to mark as favourite question ( Click again to undo )"
   class="favourite mt-2 {{ Auth::guest() ? '' : ($model->is_favorited ? 'favorited' : '') }}"
   onclick="event.preventDefault(); document.getElementById('favorite-question-{{ $model->id }}').submit();">
        <span class="favourites-count">
            <i class="fas fa-star fa-2x"></i>
        </span>
        {{ $model->votes_count }}
</a>
<form id="favorite-question-{{ $model->id }}" action="/questions/{{ $model->id }}/favorite" method="post">
    @csrf
    @if($model->is_favorited)
        @method('DELETE')
    @endif
</form>